version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
  app:
    build:
      context: .
    image: poketrades
    ports:
      - "3000:3000"
volumes:
  postgres-db:
