import "~/styles/globals.css";
import { inter } from "~/app/fonts";

import { GoogleAnalytics } from "@next/third-parties/google";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { TopNav } from "./_components/topnav";
import { Footer } from "./_components/footer";
import { Toaster } from "~/components/ui/toaster";
import NextTopLoader from "nextjs-toploader";
import { AppContextProvider } from "./_components/reducers";

export const metadata: Metadata = {
  title: "PokeTrades",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <SessionProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>
        <body className={`${inter.className} antialiased`}>
          <NextTopLoader />
          <div className="grid min-h-screen grid-rows-[auto,1fr]">
            <AppContextProvider>
              <TopNav />
              {children}
            </AppContextProvider>
            <Toaster />
            <Footer />
          </div>
        </body>
        {/* <GoogleAnalytics gaId="G-BNX08YMCR9" /> */}
      </html>
    </SessionProvider>
  );
}
